---
# tasks file for prereqs

- name: Garantindo pacotes basicos para nosso BlueGreen
  package:
   name: 
    - docker-ce
    - nginx
    - python-pip

- name: Install Docker-py
  pip:
   name: docker-py

- name: Garantindo servicos do docker e nginx rodando
  service:
   name: "{{item}}"
   state: started
  with_items:
   - nginx
   - docker






 
